/*
 * Copyright  2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.0
processor: LPC812
package_id: LPC812M101JDH20
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_swm.h"
#include "pin_mux.h"
#include "fsl_gpio.h"
#include  "LPC812.h"



/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
#define EXAMPLE_GPIO_BASE  (GPIO_BASE)
#define EXAMPLE_GPIO_MASTER ((GPIO_Type*)EXAMPLE_GPIO_BASE)
#define FSL_FEATURE_GPIO_HAS_INTERRUPT (1)
gpio_pin_config_t config = {
    .pinDirection = kGPIO_DigitalInput,  // Configurar el puerto como entrada digital
    .outputLogic = 0                   // Establecer el nivel lógico inicial en 0
};
gpio_interrupt_config_t int_config ={
		.mode = kGPIO_PinIntEnableLevel,
		.polarity = kGPIO_PinIntEnableHighOrRise
};



void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: USART0, signal: TXD, pin_signal: PIO0_6}
  - {pin_num: '12', peripheral: USART0, signal: RXD, pin_signal: PIO0_1}
  - {pin_num: '9', peripheral: I2C0, signal: SDA, pin_signal: PIO0_10}
  - {pin_num: '8', peripheral: I2C0, signal: SCL, pin_signal: PIO0_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for switch matrix.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Swm);
	//Chip_GPIO_Init(LPC_GPIO_PORT);

   // Inicio del puerto
    GPIO_PortInit(EXAMPLE_GPIO_MASTER,0);
    //Inicio del pin
    GPIO_PinInit(EXAMPLE_GPIO_MASTER,0,0,&config);

  /*  void configureInterruptPin(void) {
    	//gpio_interrupt_config_t aux;

        // Configurar el modo de disparo de la interrupción (puede ser kGPIO_IntLowLevel, kGPIO_IntHighLevel, kGPIO_IntRisingEdge, kGPIO_IntFallingEdge o kGPIO_IntRisingOrFallingEdge)
    	//int_config.mode = kGPIO_PinIntEnableLevel;

        // Configurar la polaridad de la interrupción (puede ser kGPIO_IntActiveLow o kGPIO_IntActiveHigh)
    	//int_config.polarity = kGPIO_PinIntEnableHighOrRise;

        // Configurar la función de interrupción para el pin específico
    	GPIO_SetPinInterruptConfig(EXAMPLE_GPIO_MASTER, 0, 0, &int_config);

        // Habilitar la interrupción en el NVIC (Nested Vectored Interrupt Controller)

    }*/


    /* USART0_TXD connect to P0_6*/
   SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_6);

    /* USART0_RXD connect to P0_1 */
   SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_1);

    /* I2C1_SDA connect to P0_10 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C_SDA, kSWM_PortPin_P0_10);

    /* I2C1_SCL connect to P0_11 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C_SCL, kSWM_PortPin_P0_11);

    SWM_SetMovablePinSelect(SWM0, kSWM_GPIO_INT_BMAT, kSWM_PortPin_P0_0);
    GPIO_SetPinInterruptConfig(EXAMPLE_GPIO_MASTER, 0, 0, &int_config);



    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
